[languages]

  [languages.en]
    languageName = "English"
    languageCode = "en"
    weight = 1

  [languages.zh-hant]
    languageName = "漢語"
    languageCode = "zh-Hant"
    weight = 2
    contentDir = "content/zh-hant"
