[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"   # 更穩定的錨點生成
  [markup.tableOfContents]
    startLevel = 2  # 從 H2 起
    endLevel   = 4  # 到 H4 止（可依喜好調）
    ordered    = false
