[[main]]
name = "首頁"
url  = "/zh-hant/"
weight = 1

[[main]]
name = "文章"
url  = "/zh-hant/posts/"
weight = 2

[[main]]
name = "標籤"
url  = "/zh-hant/tags/"
weight = 3

[[main]]
name = "搜尋"
url  = "/zh-hant/search/"
weight = 4
