# English menus
[[languages.en.menu.main]]
name = "Home"
url  = "/"
weight = 1

[[languages.en.menu.main]]
name = "Posts"
url  = "/posts/"
weight = 2

[[languages.en.menu.main]]
name = "Tags"
url  = "/tags/"
weight = 3

[[languages.en.menu.main]]
name = "Search"
url  = "/search/"
weight = 4

# 繁中選單
[[languages.zh-hant.menu.main]]
name = "首頁"
url  = "/zh-hant/"
weight = 1

[[languages.zh-hant.menu.main]]
name = "文章"
url  = "/zh-hant/posts/"
weight = 2

[[languages.zh-hant.menu.main]]
name = "標籤"
url  = "/zh-hant/tags/"
weight = 3

[[languages.zh-hant.menu.main]]
name = "搜尋"
url  = "/zh-hant/search/"
weight = 4
